<!--
Plunderludics.UnityHawk.Shared is code that is used by both the UnityHawk external tool and the Unity-side plugin.

TODO: This ideally should be moved into the UnityHawk external tool project. But right now it's needed by UnityHawkLuaLibrary
which is still inside the core project. And it's also needed on the Unity side so that also makes it more complicated.
-->

<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
	</PropertyGroup>
	<Import Project="../MainSlnCommon.props" />
	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<Analyzer Remove="@(Analyzer)" />  <!-- disable ReflectionCache to avoid the Bizhawk.Common dependency -->
	</ItemGroup>
</Project>
